<?php 

$wrapper = array('width' => '', 'class' => '', 'id' => '');

acf_add_local_field_group( array(
	'key' => 'group_69a95e42db19e',
	'title' => 'Options',
	'fields' => array(
		array(
			'key' => 'field_69a98e7a22152',
			'label' => 'Header',
			'name' => '',
			'type' => 'tab',
			'conditional_logic' => 0,
			'wrapper' => $wrapper,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69a95e43958a7',
			'label' => 'logo',
			'name' => 'logo',
			'type' => 'image',
			'conditional_logic' => 0,
			'wrapper' => $wrapper,
			'return_format' => 'array',
			'library' => 'all',
			'mime_types' => '',
			
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_69c3da63ab52f',
			'label' => 'logo negatif',
			'name' => 'logo-negatif',
			'type' => 'image',
			'conditional_logic' => 0,
			'wrapper' => $wrapper,
			'return_format' => 'array',
			'library' => 'all',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_69a9908ba255d',
			'label' => 'slogan',
			'name' => 'slogan',
			'type' => 'text',
			'conditional_logic' => 0,
			'wrapper' => $wrapper,
			'default_value' => '',
		),
		array(
			'key' => 'field_69a98e8e22153',
			'label' => 'Footer',
			'name' => '',
			'type' => 'tab',
			'conditional_logic' => 0,
			'wrapper' => $wrapper,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69aeccc7d536d',
			'label' => 'Menu Footer',
			'name' => 'menu_footer',
			'type' => 'post_object',
			'conditional_logic' => 0,
			'wrapper' => $wrapper,
			'post_type' => array(
				0 => 'page',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 1,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_69a992ba255c1',
			'label' => 'Blog',
			'name' => '',
			'type' => 'tab',
			'conditional_logic' => 0,
			'wrapper' => $wrapper,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69a992c7255c2',
			'label' => 'Titre actualités',
			'name' => 'titre_actualites',
			'type' => 'text',
			'conditional_logic' => 0,
			'wrapper' => $wrapper,
			'default_value' => '',
			
		),
		array(
			'key' => 'field_69b277de0d8e4',
			'label' => 'text_evidence',
			'name' => 'text_evidence',
			'type' => 'group',
			'conditional_logic' => 0,
			'wrapper' => $wrapper,
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_69b278070d8e5',
					'label' => 'category',
					'name' => 'category',
					'type' => 'text',
					'conditional_logic' => 0,
					'wrapper' => $wrapper,
					'default_value' => '',
					
				),
				array(
					'key' => 'field_69b279aa0d8e6',
					'label' => 'details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'conditional_logic' => 0,
					'wrapper' => $wrapper,
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_69b279bb0d8e7',
					'label' => 'paragraph',
					'name' => 'paragraph',
					'type' => 'text',
					'conditional_logic' => 0,
					'wrapper' => $wrapper,
					'default_value' => '',
				),
				array(
					'key' => 'field_69b279c60d8e8',
					'label' => 'link',
					'name' => 'link',
					'type' => 'link',
					'conditional_logic' => 0,
					'wrapper' => $wrapper,
					'return_format' => 'array',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );