<?php 

/***** Exemple ajout champs *****

    array(
        'key' => 'field_69a98e7a22152', | REQUIS ET DOIT ETRE UNIQUE
        'label' => 'Header',            | REQUIS
        'name' => '',                   | REQUIS
        'type' => 'wysiwy',             | REQUIS
        'aria-label' => '',             | FACULTATIF
        'instructions' => '',           | FACULTATIF
        'required' => 0,                | FACULTATIF
        'conditional_logic' => 0,       | FACULTATIF
        'wrapper' => array(             | FACULTATIF
            'width' => '',              | FACULTATIF
            'class' => '',              | FACULTATIF
            'id' => '',                 | FACULTATIF
        ),
    ),

    ⚠️ Note: It is important to remember that each field group’s key and each field’s key must be unique. 
    The key is a reference for ACF to find, save and load data. 
    If 2 fields or 2 groups are added using the same key, the later will override the original.

******** FIN EXEMPLE *****/

$wrapper = array('width' => '', 'class' => '', 'id' => '');

acf_add_local_field_group( array(
		'key' => 'group_69a95e42db19e',
		'title' => 'Options',
		'fields' => array(
			array(
				'key' => 'field_69a98e7a22152',
				'label' => 'Header',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_69a95e43958a7',
				'label' => 'logo',
				'name' => 'logo',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'return_format' => 'array',
				'library' => 'all',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_69c3da63ab52f',
				'label' => 'logo negatif',
				'name' => 'logo-negatif',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'return_format' => 'array',
				'library' => 'all',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_69a9908ba255d',
				'label' => 'slogan',
				'name' => 'slogan',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_displayNegatifHeader',
				'label' => 'Header négatif',
				'name' => 'header-negatif',
				'type' => 'post_object',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'post_type' => 'page',
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 1,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_69a98e8e22153',
				'label' => 'Footer',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_69bab35afaec0',
				'label' => 'text_ev',
				'name' => 'text_ev',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_69bab56dfaec1',
				'label' => 'paragraph',
				'name' => 'paragraph',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_69bab57ffaec2',
				'label' => 'contact',
				'name' => 'contact',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_69b277de0d8e4',
				'label' => 'text_evidence',
				'name' => 'text_evidence',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_69b278070d8e5',
						'label' => 'category',
						'name' => 'category',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_69b279aa0d8e6',
						'label' => 'details',
						'name' => 'details',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'default_value' => '',
						'allow_in_bindings' => 0,
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_69b279bb0d8e7',
						'label' => 'paragraph',
						'name' => 'paragraph',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_69b279c60d8e8',
						'label' => 'link',
						'name' => 'link',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'return_format' => 'array',
						'allow_in_bindings' => 0,
					),
				),
			),
			array(
				'key' => 'field_69bab885faec3',
				'label' => 'made_by',
				'name' => 'made_by',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_69aeccc7d536d',
				'label' => 'Menu Footer',
				'name' => 'menu_footer',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'post_type' => array(
					0 => 'page',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 1,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_69a992ba255c1',
				'label' => 'Blog',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_69a992c7255c2',
				'label' => 'Titre actualités',
				'name' => 'titre_actualites',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_69c67be51b9dc',
				'label' => 'megamenu',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_69c649ea5ea0d',
				'label' => 'bg-menu-image',
				'name' => 'bg-menu-image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'return_format' => 'array',
				'library' => 'all',
				
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_69c6562cf13a9',
				'label' => 'infos-contact',
				'name' => 'infos-contact',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'layout' => 'block',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Ajouter un élément',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_69c65648f13aa',
						'label' => 'site-name',
						'name' => 'site-name',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_69c6562cf13a9',
					),
					array(
						'key' => 'field_69c65676f13ac',
						'label' => 'street-name',
						'name' => 'street-name',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_69c6562cf13a9',
					),
					array(
						'key' => 'field_69c65689f13ad',
						'label' => 'locality',
						'name' => 'locality',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_69c6562cf13a9',
					),
					array(
						'key' => 'field_69c65693f13ae',
						'label' => 'tel-num',
						'name' => 'tel-num',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_69c6562cf13a9',
					),
					array(
						'key' => 'field_69c6569ef13af',
						'label' => 'mail',
						'name' => 'mail',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_69c6562cf13a9',
					),
					array(
						'key' => 'field_69c656c4f13b0',
						'label' => 'tva',
						'name' => 'tva',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_69c6562cf13a9',
					),
				),
			),
			array(
				'key' => 'field_69c5456d667c5',
				'label' => 'logo-social-media',
				'name' => 'logo-social-media',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Ajouter un élément',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_69c545e4667c6',
						'label' => 'Logo',
						'name' => 'image',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'return_format' => 'array',
						'library' => 'all',
						'allow_in_bindings' => 0,
						'preview_size' => 'medium',
						'parent_repeater' => 'field_69c5456d667c5',
					),
					array(
						'key' => 'field_69c645e5414bd',
						'label' => 'Lien',
						'name' => 'lien',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'library' => 'all',
						'allow_in_bindings' => 0,
						'preview_size' => 'medium',
						'parent_repeater' => 'field_69c5456d667c5',
					),
				),
			),
			array(
				'key' => 'field_69c54e8dc4220',
				'label' => 'cond-generales',
				'name' => 'cond-generales',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_69c646dc42379',
						'label' => 'cond',
						'name' => 'cond',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_69c6476e4237a',
						'label' => 'copyright',
						'name' => 'copyright',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
				),
			),
			array(
				'key' => 'field_69c6630950d8c',
				'label' => 'logo_bg_menu',
				'name' => 'logo_bg_menu',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'return_format' => 'array',
				'library' => 'all',
				
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_69c54da443370',
				'label' => 'menu-burger-footer',
				'name' => 'menu-burger-footer',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Ajouter un élément',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_69c54e4d43371',
						'label' => 'link',
						'name' => 'link',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => $wrapper,
						'return_format' => 'array',
						'allow_in_bindings' => 0,
						'parent_repeater' => 'field_69c54da443370',
					),
				),
			),

			array(
				'key' => 'field_69a98e8e22153fer',
				'label' => 'Partenaires',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => $wrapper,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			

			array(
				'key'            => 'field_69c545e4667c6ddd',
				'label'          => 'Titrrrrrrrrrre',
				'name'           => 'title-part',
				'type'           => 'wysiwyg',
				'wrapper'        => $wrapper,
				'return_format'  => 'array',
				'preview_size'   => 'medium',
			),

			array(
				'key'        => 'field_69c5456d667c512',
				'label'      => 'gallerie-partenaires',
				'name'       => 'gallerie-partenaires',
				'type'       => 'repeater',
				'wrapper'    => $wrapper,
				'layout'     => 'table',
				'min'        => 0,
				'max'        => 0,
				'button_label' => 'Ajouter un élément',
				'sub_fields' => array(
					array(
					'key'            => 'field_69c545e4667c6',
					'label'          => 'Image',
					'name'           => 'image',
					'type'           => 'image',
					'wrapper'        => $wrapper,
					'return_format'  => 'array',
					'preview_size'   => 'medium',
					'parent_repeater' => 'field_69c5456d667c512',
					),
					array(
					'key'            => 'field_69c645e5414bd',
					'label'          => 'Lien',
					'name'           => 'lien',
					'type'           => 'link',
					'wrapper'        => $wrapper,
					'return_format'  => 'array',
					'parent_repeater' => 'field_69c5456d667c512',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	) 
);