import "./js/animate.js";
import "./js/filter.js";
import "./js/img-hover.js";
import "./js/header.js";
import "./js/parallax.js";
import "./js/scroll-top.js";
import "./js/skeleton.js";
import "./js/swiper.js";
import "./js/accordeon.js";
